' ******************************************************************************
' swxJRNL.swj - journal recorded on 03/27/18 by EMLAdmin
' *****************************************************************************
Dim swApp As Object

Dim Part As Object
Dim boolstatus As Boolean
Dim longstatus As Long, longwarnings As Long

Sub main()

Set swApp = Application.SldWorks

swApp.ActivateDoc2 "slide tab.SLDPRT", False, longstatus
Set Part = swApp.ActiveDoc
Set Part = swApp.ActiveDoc
Dim myModelView As Object
Set myModelView = Part.ActiveView
myModelView.FrameLeft = 0
myModelView.FrameTop = 0
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized

' Redraw
Part.GraphicsRedraw2
Set Part = swApp.ActiveDoc
Set myModelView = Part.ActiveView
myModelView.FrameLeft = 0
myModelView.FrameTop = 22
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
swApp.ActivateDoc2 "assemble.SLDASM", False, longstatus
Set Part = swApp.ActiveDoc

' Take Snapshot
Dim swSnapShot As SnapShot
Set swSnapShot = Part.ModelViewManager.AddSnapShot("Home")
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.010308350894591534, -0.022263255025439528, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0034361169648638441, -0.0074210850084798436, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0034361169648638441, 0, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0034361169648638441, -0.0074210850084798436, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0068722339297276882, -0.0074210850084798436, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0068722339297276882, -0.014842170016959687, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0068722339297276882, 0, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0068722339297276882, -0.014842170016959687, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.010308350894591534, -0.0074210850084798436, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0068722339297276882, -0.0074210850084798436, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.017180584824319219, -0.014842170016959687, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.024052818754046908, -0.029684340033919374, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.048105637508093817, -0.044526510050879056, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.037797286613502283, -0.051947595059358899, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.034361169648638439, -0.029684340033919374, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.037797286613502283, -0.037105425042399214, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.044669520543229972, -0.044526510050879056, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.075594573227004566, -0.051947595059358899, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.030925052683774594, -0.022263255025439528, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.054977871437821506, -0.037105425042399214, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.027488935718910753, -0.014842170016959687, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.024052818754046908, -0.0074210850084798436, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.024052818754046908, -0.014842170016959687, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.017180584824319219, 0, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.010308350894591534, -0.0074210850084798436, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.010308350894591534, 0, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.010308350894591534, 0, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.010308350894591534, 0, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0068722339297276882, 0, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.010308350894591534, 0, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0068722339297276882, 0, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0068722339297276882, 0, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0034361169648638441, 0, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.010308350894591534, 0, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0068722339297276882, 0.0074210850084798436, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0034361169648638441, 0.014842170016959687, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0068722339297276882, 0.0074210850084798436, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.010308350894591534, 0.0074210850084798436, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0068722339297276882, 0.014842170016959687, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.013744467859455376, 0.029684340033919374, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.010308350894591534, 0.022263255025439528, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.010308350894591534, 0.037105425042399214, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.013744467859455376, 0.044526510050879056, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.017180584824319219, 0.066789765076318591, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.013744467859455376, 0.051947595059358899, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.013744467859455376, 0.051947595059358899, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.017180584824319219, 0.074210850084798427, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.010308350894591534, 0.051947595059358899, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.010308350894591534, 0.051947595059358899, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.010308350894591534, 0.051947595059358899, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0068722339297276882, 0.051947595059358899, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0068722339297276882, 0.044526510050879056, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0068722339297276882, 0.044526510050879056, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0034361169648638441, 0.059368680067838749, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0034361169648638441, 0.044526510050879056, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0034361169648638441, 0.037105425042399214, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0034361169648638441, 0.044526510050879056, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0034361169648638441, 0.022263255025439528, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.022263255025439528, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.014842170016959687, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0074210850084798436, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.014842170016959687, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0074210850084798436, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0074210850084798436, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0074210850084798436, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0074210850084798436, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0074210850084798436, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0074210850084798436, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0074210850084798436, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0074210850084798436, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0074210850084798436, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.014842170016959687, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0074210850084798436, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0074210850084798436, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0074210850084798436, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0074210850084798436, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.014842170016959687, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0074210850084798436, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0074210850084798436, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0074210850084798436, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0034361169648638441, 0, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.010308350894591534, 0, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0068722339297276882, 0, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.010308350894591534, 0, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.010308350894591534, 0, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0034361169648638441, 0, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.017180584824319219, 0, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0068722339297276882, 0, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.010308350894591534, 0, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0068722339297276882, 0, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0034361169648638441, -0.0074210850084798436, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0034361169648638441, 0, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.0074210850084798436, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0034361169648638441, 0, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0034361169648638441, 0, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.0074210850084798436, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0034361169648638441, 0, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0034361169648638441, 0, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0034361169648638441, 0, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0034361169648638441, 0, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0034361169648638441, -0.0074210850084798436, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0068722339297276882, 0, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0068722339297276882, -0.0074210850084798436, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0068722339297276882, 0, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0068722339297276882, 0, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0068722339297276882, -0.0074210850084798436, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.017180584824319219, -0.022263255025439528, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.010308350894591534, 0, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.013744467859455376, -0.014842170016959687, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.024052818754046908, -0.022263255025439528, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.017180584824319219, -0.014842170016959687, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.020616701789183067, -0.022263255025439528, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.020616701789183067, -0.014842170016959687, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.024052818754046908, -0.014842170016959687, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.024052818754046908, -0.014842170016959687, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.013744467859455376, -0.0074210850084798436, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.024052818754046908, -0.014842170016959687, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.010308350894591534, -0.0074210850084798436, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.010308350894591534, 0, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.013744467859455376, 0, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0068722339297276882, -0.0074210850084798436, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0068722339297276882, 0, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0068722339297276882, 0, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0034361169648638441, 0, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0034361169648638441, 0, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0068722339297276882, 0, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.0074210850084798436, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0034361169648638441, 0, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0034361169648638441, 0, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0034361169648638441, 0, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0034361169648638441, 0, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0034361169648638441, 0, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0068722339297276882, -0.0074210850084798436, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0034361169648638441, -0.0074210850084798436, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0034361169648638441, 0, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0034361169648638441, 0, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0034361169648638441, 0, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0034361169648638441, 0, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0034361169648638441, 0, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0034361169648638441, 0, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0034361169648638441, 0, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0068722339297276882, 0, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0068722339297276882, 0, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0034361169648638441, 0, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0034361169648638441, 0, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0068722339297276882, 0, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0074210850084798436, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0034361169648638441, 0, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0034361169648638441, 0.0074210850084798436, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0034361169648638441, 0.0074210850084798436, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0074210850084798436, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0034361169648638441, 0.0074210850084798436, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.014842170016959687, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0034361169648638441, 0.0074210850084798436, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0074210850084798436, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0034361169648638441, 0, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0074210850084798436, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0074210850084798436, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0074210850084798436, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0074210850084798436, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0074210850084798436, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0074210850084798436, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0074210850084798436, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0034361169648638441, 0, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0074210850084798436, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0034361169648638441, 0.0074210850084798436, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0034361169648638441, 0.0074210850084798436, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0034361169648638441, 0.0074210850084798436, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0034361169648638441, 0.0074210850084798436, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0034361169648638441, 0, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0034361169648638441, 0.022263255025439528, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0068722339297276882, 0, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0034361169648638441, 0.014842170016959687, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0068722339297276882, 0.0074210850084798436, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0068722339297276882, 0.0074210850084798436, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0034361169648638441, 0.0074210850084798436, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0034361169648638441, 0.0074210850084798436, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0068722339297276882, 0.014842170016959687, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0068722339297276882, 0.0074210850084798436, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0034361169648638441, 0.0074210850084798436, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0034361169648638441, 0.0074210850084798436, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0068722339297276882, 0.0074210850084798436, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0068722339297276882, 0.0074210850084798436, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0034361169648638441, 0.0074210850084798436, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0074210850084798436, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0034361169648638441, 0, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0074210850084798436, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0034361169648638441, 0, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0034361169648638441, 0, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0034361169648638441, 0.0074210850084798436, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0074210850084798436, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0074210850084798436, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0068722339297276882, 0.0074210850084798436, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0034361169648638441, 0.0074210850084798436, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0034361169648638441, 0, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0034361169648638441, 0, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0034361169648638441, 0, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0034361169648638441, 0.0074210850084798436, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0034361169648638441, 0, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0074210850084798436, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0034361169648638441, 0, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.014842170016959687, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0034361169648638441, 0, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0074210850084798436, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0074210850084798436, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0074210850084798436, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.0074210850084798436, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.022263255025439528, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.0074210850084798436, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.0074210850084798436, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.0074210850084798436, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.0074210850084798436, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.0074210850084798436, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.0074210850084798436, -0.006810000000001537, -0.0033566031212330927, -0.012710189024119245

' Roll View
Dim swModelView As Object
Set swModelView = Part.ActiveView
swModelView.RollBy 0
boolstatus = Part.Extension.SelectByRay(-0.0041331307985501553, 0.033810469017627298, -0.0080536144319829361, 0.99773698479607176, -0.05251644973512902, -0.041987279945970513, 0.0003486684627844541, 2, False, 0, 0)
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.017180584824319219, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.017180584824319219, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.027488935718910753, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.024052818754046908, -0.014842170016959687
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.044669520543229972, -0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.034361169648638439, -0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.024052818754046908, -0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.024052818754046908, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.037797286613502283, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.020616701789183067, -0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.024052818754046908, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.030925052683774594, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.024052818754046908, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.020616701789183067, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.013744467859455376, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.020616701789183067, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.017180584824319219, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.013744467859455376, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.013744467859455376, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.010308350894591534, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.013744467859455376, 0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.010308350894591534, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.017180584824319219, 0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.013744467859455376, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, 0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.013744467859455376, 0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.010308350894591534, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.010308350894591534, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.010308350894591534, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.013744467859455376, 0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, 0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, 0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, 0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, 0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, 0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.010308350894591534, 0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.010308350894591534, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, 0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.010308350894591534, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.010308350894591534, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.010308350894591534, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.010308350894591534, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.010308350894591534, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.013744467859455376, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.010308350894591534, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.010308350894591534, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.010308350894591534, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.010308350894591534, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.010308350894591534, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.010308350894591534, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, -0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, -0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.010308350894591534, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, -0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, -0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.010308350894591534, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.010308350894591534, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, -0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, -0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.010308350894591534, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.017180584824319219, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.010308350894591534, -0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.010308350894591534, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, -0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.010308350894591534, -0.014842170016959687
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, -0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, -0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.010308350894591534, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, -0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, -0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, 0

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0034361169648638441, 0.0074210850084798436

' Zoom In/Out (MouseWheel)
Set swModelView = Part.ActiveView
swModelView.Scale2 = 1.9734943407273886
Dim swTranslation() As Double
ReDim swTranslation(0 To 2) As Double
swTranslation(0) = 0.084074292104232395
swTranslation(1) = -0.048582735630562784
swTranslation(2) = -0.13051540517095106
Dim swTranslationVar As Variant
swTranslationVar = swTranslation
Dim swMathUtils As Object
Set swMathUtils = swApp.GetMathUtility()
Dim swTranslationVector As MathVector
Set swTranslationVector = swMathUtils.CreateVector((swTranslationVar))
swModelView.Translation3 = swTranslationVector
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.029684340033919374
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0068722339297276882, 0.014842170016959687
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0034361169648638441, 0.014842170016959687
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0068722339297276882, 0.022263255025439528
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0034361169648638441, 0.029684340033919374
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0034361169648638441, 0.022263255025439528
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.010308350894591534, 0.029684340033919374
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0034361169648638441, 0.022263255025439528
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0034361169648638441, 0.029684340033919374
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0068722339297276882, 0.014842170016959687
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0068722339297276882, 0.022263255025439528
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0034361169648638441, 0.014842170016959687
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0034361169648638441, 0.022263255025439528
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0068722339297276882, 0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0034361169648638441, 0.014842170016959687
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0034361169648638441, 0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0034361169648638441, 0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0034361169648638441, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.022263255025439528
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.014842170016959687
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, -0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0034361169648638441, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0034361169648638441, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0068722339297276882, -0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0034361169648638441, -0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.010308350894591534, -0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0068722339297276882, -0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.010308350894591534, -0.014842170016959687
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.017180584824319219, -0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.010308350894591534, -0.014842170016959687
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.017180584824319219, -0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.024052818754046908, -0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.017180584824319219, -0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.017180584824319219, -0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.037797286613502283, -0.014842170016959687
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.020616701789183067, -0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.020616701789183067, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.030925052683774594, -0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.030925052683774594, -0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.030925052683774594, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.030925052683774594, -0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.041233403578366135, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.034361169648638439, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.027488935718910753, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.027488935718910753, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.041233403578366135, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.024052818754046908, 0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.027488935718910753, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.027488935718910753, 0.014842170016959687
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.024052818754046908, 0.014842170016959687
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.017180584824319219, 0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.024052818754046908, 0.014842170016959687
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.013744467859455376, 0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.017180584824319219, 0.014842170016959687
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.010308350894591534, 0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.013744467859455376, 0.014842170016959687
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.013744467859455376, 0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0068722339297276882, 0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0068722339297276882, 0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0068722339297276882, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0034361169648638441, 0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0068722339297276882, 0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0034361169648638441, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0034361169648638441, 0

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
boolstatus = Part.Extension.SelectByRay(-0.0041331307987206856, 0.049234293004474239, -0.031968849360509921, 0.76797815502658229, -0.63965863304440196, 0.032347899062131653, 0.00041840215534134489, 2, False, 0, 0)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByRay(-0.0041331307987206856, 0.059043843729114087, -0.016613364456564028, 0.76797815502658229, -0.63965863304440196, 0.032347899062131653, 0.00041840215534134489, 2, False, 0, 0)
Part.OpenCompFile

' Open
Set Part = swApp.OpenDoc6("G:\Juyeong\DigitalGlass\CameraHolderV3\slide tab.SLDPRT", 1, 0, "", longstatus, longwarnings)
Set Part = swApp.ActiveDoc
Set myModelView = Part.ActiveView
myModelView.FrameLeft = 0
myModelView.FrameTop = 0
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
swApp.ActivateDoc2 "slide tab.SLDPRT", False, longstatus
Set Part = swApp.ActiveDoc
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByRay(0.0072815620890225169, -0.0028466597950896916, 0.0017780000000016116, 0, 0, -1, 0.00038547275080215952, 2, False, 0, 0)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByRay(-0.0036023744042149169, -0.00080592170260767638, 0.0017780000000016116, 0, 0, -1, 0.00038547275080215952, 2, False, 0, 0)
boolstatus = Part.Extension.SelectByRay(-0.012105449789556674, 0.021415448637752115, 0.0017780000000016116, 0, 0, -1, 0.00038547275080215952, 2, False, 0, 0)

' Redraw
Part.GraphicsRedraw2
Part.ClearSelection2 True

' Zoom In/Out (MouseWheel)
Set swModelView = Part.ActiveView
swModelView.Scale2 = 1.7850684300338442
ReDim swTranslation(0 To 2) As Double
swTranslation(0) = 0.023268580060221242
swTranslation(1) = 0.0005279111026898146
swTranslation(2) = -8.92534215017083e-005
swTranslationVar = swTranslation
Set swMathUtils = swApp.GetMathUtility()
Set swTranslationVector = swMathUtils.CreateVector((swTranslationVar))
swModelView.Translation3 = swTranslationVector

' Zoom In/Out (MouseWheel)
Set swModelView = Part.ActiveView
swModelView.Scale2 = 1.4875570250282035
ReDim swTranslation(0 To 2) As Double
swTranslation(0) = 0.024288102431136743
swTranslation(1) = 0.00043992591890817885
swTranslation(2) = -7.4377851251423595e-005
swTranslationVar = swTranslation
Set swMathUtils = swApp.GetMathUtility()
Set swTranslationVector = swMathUtils.CreateVector((swTranslationVar))
swModelView.Translation3 = swTranslationVector

' Zoom In/Out (MouseWheel)
Set swModelView = Part.ActiveView
swModelView.Scale2 = 1.2396308541901697
ReDim swTranslation(0 To 2) As Double
swTranslation(0) = 0.025137704406899702
swTranslation(1) = 0.00036660493242348931
swTranslation(2) = -6.198154270951966e-005
swTranslationVar = swTranslation
Set swMathUtils = swApp.GetMathUtility()
Set swTranslationVector = swMathUtils.CreateVector((swTranslationVar))
swModelView.Translation3 = swTranslationVector

' Zoom In/Out (MouseWheel)
Set swModelView = Part.ActiveView
swModelView.Scale2 = 1.0330257118251416
ReDim swTranslation(0 To 2) As Double
swTranslation(0) = 0.025845706053368753
swTranslation(1) = 0.00030550411035290542
swTranslation(2) = -5.1651285591266379e-005
swTranslationVar = swTranslation
Set swMathUtils = swApp.GetMathUtility()
Set swTranslationVector = swMathUtils.CreateVector((swTranslationVar))
swModelView.Translation3 = swTranslationVector

' Zoom In/Out (MouseWheel)
Set swModelView = Part.ActiveView
swModelView.Scale2 = 1.2446092913555924
ReDim swTranslation(0 To 2) As Double
swTranslation(0) = -0.0028512319494696744
swTranslation(1) = -0.00034359659682094937
swTranslation(2) = -6.2230464567790831e-005
swTranslationVar = swTranslation
Set swMathUtils = swApp.GetMathUtility()
Set swTranslationVector = swMathUtils.CreateVector((swTranslationVar))
swModelView.Translation3 = swTranslationVector

' Zoom In/Out (MouseWheel)
Set swModelView = Part.ActiveView
swModelView.Scale2 = 1.499529266693485
ReDim swTranslation(0 To 2) As Double
swTranslation(0) = -0.037425856049274994
swTranslation(1) = -0.0011256456416087115
swTranslation(2) = -7.4976463334687751e-005
swTranslationVar = swTranslation
Set swMathUtils = swApp.GetMathUtility()
Set swTranslationVector = swMathUtils.CreateVector((swTranslationVar))
swModelView.Translation3 = swTranslationVector

' Zoom In/Out (MouseWheel)
Set swModelView = Part.ActiveView
swModelView.Scale2 = 1.8066617671005845
ReDim swTranslation(0 To 2) As Double
swTranslation(0) = -0.02128173706453098
swTranslation(1) = -0.011845653096602581
swTranslation(2) = -9.0333088355045479e-005
swTranslationVar = swTranslation
Set swMathUtils = swApp.GetMathUtility()
Set swTranslationVector = swMathUtils.CreateVector((swTranslationVar))
swModelView.Translation3 = swTranslationVector
Set Part = swApp.ActiveDoc
Set myModelView = Part.ActiveView
myModelView.FrameLeft = 0
myModelView.FrameTop = 0
swApp.ActivateDoc2 "assemble.SLDASM", False, longstatus
Set Part = swApp.ActiveDoc
Set Part = swApp.ActiveDoc
Set myModelView = Part.ActiveView
myModelView.FrameLeft = 0
myModelView.FrameTop = 22
swApp.ActivateDoc2 "slide tab.SLDPRT", False, longstatus
Set Part = swApp.ActiveDoc
Set Part = swApp.ActiveDoc
Set myModelView = Part.ActiveView
myModelView.FrameLeft = 0
myModelView.FrameTop = 0
Set Part = swApp.ActiveDoc
Set myModelView = Part.ActiveView
myModelView.FrameLeft = 0
myModelView.FrameTop = 0
Set Part = swApp.ActiveDoc
Set myModelView = Part.ActiveView
myModelView.FrameLeft = 0
myModelView.FrameTop = 0
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized

' Close Document
swPart = Nothing
Set Part = Nothing
swApp.CloseDoc "slide tab.SLDPRT"
Set Part = swApp.ActiveDoc
Set myModelView = Part.ActiveView
myModelView.FrameLeft = 0
myModelView.FrameTop = 22
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
swApp.ActivateDoc2 "assemble.SLDASM", False, longstatus
Set Part = swApp.ActiveDoc

' Save
Dim swErrors As Long
Dim swWarnings As Long
boolstatus = Part.Save3(1, swErrors, swWarnings)

' Close Document
swAssembly = Nothing
Set Part = Nothing
swApp.CloseDoc "assemble.SLDASM"
swApp.ExitApp
End Sub
